branches:
  only:
    - master
    - /\d+\.\d+\.x/

git:
  depth: false

dist: xenial

language: node_js
node_js: 12

cache:
  directories:
    - $HOME/.npm
    - $HOME/.sonar/cache
    - node_modules

env:
  - TEST_SUITE=tslint
  - TEST_SUITE=build-storybook
  - TEST_SUITE=test-unit
  - TEST_SUITE=pep8

before_install:
  - pip install --user pycodestyle

install:
  - npm install

script:
  - npm run $TEST_SUITE
  # - sonar-scanner

addons:
  sonarcloud:
    organization: "brave"
    token:
      secure: "V5gSEhcLpqPEsJQU1rz064Z04WIK18uLk4wMJYiYKoWVSry5Q8rIQRiaFGE5mzem07lBL+H5kJyw9e/Ik7h9wEDgGLzCAej6eX60TY7FYRBP0lWnJ5VupDjG3Mwg1KCeBhg8KjlPGefHDm8DjqLreOnWc6Dy0DtwZy4dRlnrKGCKxzNHfHpcRshMGVDhoh7c6GpzdlMlSdjotD+eT2OsCeKhZvEnm8wLaLy9dQSAVdJ9BBk8uUTNZ0GvgUW6fNzsW5B7BSq7ANbD6lQD/YUSCAMS1IpXHdjdtUuQJdVfaWt3sa9+4eA7MQuwtZv110TVjnK/WDTU2B8qjjEPSPIJblhJ7thVojlCvm8Z71dWxFmqIc3ohfX1EquTrnVLuP5rKZvkMYYeICWjOqKHOKr87HRUUBeEzh8XbUMsyJeO8xkcOAa+QN/vsLwGRZKlXnse40JsZBeocuMsNar2oCx36DxG8M9OZw2/4Ynl3yKVtsc3Zx+mQkzfUnWRw97IpR4rFE/ZRJw9prdYbHUa91xGIBHYUX+GQjzdOSZbTcuVUrC+knK9uMjxiFT4UkQlrnU9t5l9li4W1F8s/lKZtNYqbPoB6c5LzFAgZuotsHT5484yru6xxtMBYsy1rupOqumFwe/Eza7mgm0nCBrrxXz3Tk+oFZ6T+VaOj1i7iwR8NVc="
